### ISSUE TITLE
Styling news cards on Home page. 

### ISSUE THREAD

**Issue by jackabald** [jackabald/NuancedNews#37]
1. News cards should be spaced evenly. Right now, CNN and NYT are bordering each other. Either create some padding there or create a border for these cards (whatever you think looks better, play around and see what you think looks the nicest)

2. Style the "pre" hover div to include either a picture of the logo or a different picture that represents the company; the pre-hover style should be very simple and easy on the eyes but also professional and sleak looking. 

![Drawing-1 sketchpad](https://github.com/user-attachments/assets/67d495ef-d964-4309-a177-5e68db1fc75b)

Most if not all of these fixes will be in the NewCards.jsx component and NewsCards.css

**Comment by jackabald** [comment]
@ShubhamNakashe

**Comment by ShubhamNakashe** [comment]
Yeah Sure, I would love to solve this issue.
Task is just to add styling to pre hovered new cards and space them evenly right ??

**Comment by jackabald** [comment]
@ShubhamNakashe 
Correct, that's it.

**Comment by ShubhamNakashe** [comment]
![image](https://github.com/user-attachments/assets/ecff4ba9-5e4b-428d-9169-30fa0b2f5236)


Is it ok ?? 
Shall I send PR request ??

**Comment by jackabald** [comment]
Looks great send the PR!!!
