### ISSUE TITLE
Update the more page so that the articles are correctly styled.

### ISSUE THREAD

**Issue by jackabald** [jackabald/NuancedNews#43]
The articles on the more page are the reused `Article.jsx` component used on the home page. 

To style these correctly, we may need to make a new component similar to the Article, but it will be only used on the More page.

Please ask questions if you need help. It should be pretty straightforward.

**Comment by mayurbodhare** [comment]
assign it to me #43

**Comment by jackabald** [comment]
Assigned to you!
