### ISSUE TITLE
Bug: bookmark button no longer turns red after clicking.

### ISSUE THREAD

**Issue by jackabald** [jackabald/NuancedNews#5]

**Comment by krishchvn** [comment]
Hey, could I take a stab at this?

**Comment by jackabald** [comment]
> Hey, could I take a stab at this?

Please do!

**Comment by krishchvn** [comment]
Hi Jack,

I'm facing FileNotFound error in /Backend for "rss_feed.json". 

![image](https://github.com/jackabald/NuancedNews/assets/58606754/1170428d-9c1f-4122-89f8-734572bde6af)

Can you please check if you've uploaded it on github?

**Comment by jackabald** [comment]
run "python rss_parser.py" this script will create the rss_feed.json file.

**Comment by krishchvn** [comment]
Hey Jack,

Is this fine? 
[recording-2024-07-10-00-24-06.webm](https://github.com/jackabald/NuancedNews/assets/58606754/82c7d805-f134-46b6-94ba-0db6d248bac6)

Please let me know if any changes required.

**Comment by jackabald** [comment]
I would prefer it to be fully highlighted red instead of just the border. This was working in a previous commit I am unsure what happened to its functionality. 

Thank you!

**Comment by krishchvn** [comment]
Heyy,

[recording-2024-07-10-01-24-14.webm](https://github.com/jackabald/NuancedNews/assets/58606754/f786a40f-c8c7-4d9b-b524-e8725875d5f4)

How about this?

**Comment by jackabald** [comment]
That looks great. Please create a pull request.

**Comment by krishchvn** [comment]
Hi. I've created a pull request. 
Thanks. Happy to help!
