### ISSUE TITLE
feat: Bookmarked articles should show up in users profile page. 

### ISSUE THREAD

**Issue by jackabald** [jackabald/NuancedNews#8]
When a user bookmarks an articles I want the articles to be saved to the users account and be displayed on their profile.

**Comment by kabeer95** [comment]
hey @jackabald If this is a paid issue , assign me i can fix it

**Comment by jackabald** [comment]
This is not paid. Just open for contributors.

**Comment by Prism194** [comment]
Hello, I made Flask application in the past and I want to help you. Can you give me an instruction about variables for Firebase Web SDK

**Comment by jackabald** [comment]
Right-click the page and look at the console logs. You need to run 'python rss_parser.py' before running the flask server on the backend.

**Comment by Prism194** [comment]
So you want not only the function to save articles in your profile, but also the function to log in? Because currently, the backend doesn't seem to have the function to sign up and log in. I can help you all if you want, but I think I'll need a week or so.

**Comment by jackabald** [comment]
So currently, I can signup and signin to an extent, 

![Capture](https://github.com/jackabald/NuancedNews/assets/106791028/bf990d29-ea82-4f2c-8f7d-af3bd3869096)

but this is the extent of that ability, and in firebase I can see those log ins. I can make two issues because there is A LOT of work to be done with the profile portion. I would start with just trying to allow users to log in and start logged in even after reloading the page. Then i would maybe work towards setting up firestore or realtime database to handle user information. and then you can start working on bookmarked articles showing up in a users profile. 

I appreciate the help, and if you have any other ideas or even want to switch away from firebase please let me know.

**Comment by jackabald** [comment]
Continuing, If you would like to take a stab at all of this, and your not super comfortable with firebase or you want experience with a different user auth/database or you think one will work better for the needs of the project please do. 

This project is still very clearly in development so we have the ability to completely shift if your more comfortable with a different stack.

**Comment by Prism194** [comment]
Okay, I'll do it in my ability and condition.

**Comment by jackabald** [comment]
Hey,

Any updates on this issue?

Thanks!

**Comment by jackabald** [comment]
Hey! 

Are you still working on this? any updates? or should I unassign you?

**Comment by Prism194** [comment]
Sorry for not responding. I had to concentrate on something else in the meantime because it urgently happened. But your repository is very interesting. I can't participate right away, but I'll keep watching.

**Comment by jackabald** [comment]
No worries.
I appreciate it!
